name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

     - name: Setup Node
       uses: actions/setup-node@v3
        with:
          node-version: 18.x

     - uses: actions/cache@v3
       id: yarn-cache
       with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: yarn deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}